---

- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"
    use: "systemd"

- name: Get attribute /etc/hosts
  stat:
    path: /etc/hosts
  register: get_stat

- name: Chattr -i /etc/hosts
  file:
    path: /etc/hosts
    attributes: '-i'
  changed_when: False
  when: '"immutable" in get_stat.stat.attributes'

- name: Deploy file hosts template
  template:
    src: templates/hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644

# - name: Update /etc/hosts
#   blockinfile:
#       path: /etc/hosts
#       create: yes
#       block: |
#         127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
#         ::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
#         {{ ansible_ssh_host }} {{ inventory_hostname }}

- name: Chattr +i /etc/hosts
  file:
    path: /etc/hosts
    attributes: '+i'
  changed_when: False

- name: Change motd
  copy: 
    src: scripts/dynomotd.sh
    dest: /etc/profile.d/dynomotd.sh
    owner: root
    group: root
    mode: '0644'
    backup: no

- name: Check /etc/NetworkManager/NetworkManager.conf exists
  stat:
    path: /etc/NetworkManager/NetworkManager.conf
  register: stat_result

- name: Make sure line 'dns=none' is set in /etc/NetworkManager/NetworkManager.conf
  ini_file:
    path: /etc/NetworkManager/NetworkManager.conf
    state: present
    no_extra_spaces: yes
    section: main
    option: dns
    value: none
    owner: root
    group: root
    mode: 0644
    backup: yes
  when: stat_result.stat.exists
  notify:
    - restart NetworkManager

- name: Set timezone {{ set_timezone }}
  timezone:
    name: "{{ set_timezone }}"

- name: Check locale
  lineinfile:
    path: /etc/locale.conf
    line: "LANG={{ set_locale }}"
    state: present
  check_mode: yes
  register: need_set_locale

- name: Set locale {{ set_locale }}
  command: "localectl set-locale LANG={{ set_locale }}"
  when: need_set_locale.changed

- name: Update {{ ansible_distribution }} hosts
  yum:
    update_cache: true
    update_only: true

- name: Install packages
  package:
    name: "{{ item }}"
  with_items: "{{ packages[ansible_distribution][ansible_distribution_major_version] }}"