---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu
    dockerfile: ../common/Dockerfile.j2
    image: ubuntu:22.04
    pre_build_image: false
  - name: centos
    dockerfile: ../common/Dockerfile.j2
    image: centos:centos8
    pre_build_image: false
provisioner:
  name: ansible
verifier:
  name: ansible
